# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'app/services/recipe_services/parser.rb'
    - 'app/services/recipe_services/ingredient.rb'