default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: tonights_special_development

test:
  <<: *default
  database: tonights_special_test

# Keep your production config as is
production:
  primary: &primary_production
    <<: *default
    database: tonights_special_production
    username: tonights_special
    password: <%= ENV["TONIGHTS_SPECIAL_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tonights_special_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tonights_special_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tonights_special_production_cable
    migrations_paths: db/cable_migrate