name: Test Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-modules-cache: true
          cache: yarn

      - name: Install dependencies
        run: |
          bundle install
          yarn install

      - name: Run frontend tests
        run: yarn test --coverage

      - name: Run backend tests
        run: bundle exec rspec

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info,./coverage/.resultset.json